"""Render a ReliabilityReport as Markdown for GitHub (PR comments + job summaries)."""

from __future__ import annotations

from volo_reliability import ReliabilityReport

_VERDICT = {"ship": "✅ **SHIP**", "no_ship": "❌ **NO-SHIP**"}
_METRIC_LABELS = {
    "trajectory_determinism": "Trajectory determinism",
    "decision_determinism": "Decision determinism",
    "faithfulness": "Faithfulness",
    "consistency_under_repetition": "Consistency under repetition",
}


def report_markdown(report: ReliabilityReport) -> str:
    """A compact, PR-comment-friendly reliability summary."""
    verdict = _VERDICT.get(report.verdict, report.verdict)
    lines: list[str] = [
        f"## 🛫 Volo reliability — {verdict}",
        "",
        f"Replayed **{len(report.scenarios)}** adversarial scenarios against the agent "
        f"(threshold ≥ {report.fail_under:.2f}).",
        "",
        "| Metric | Score | |",
        "|---|---|---|",
    ]
    for key, value in report.aggregate.items():
        label = _METRIC_LABELS.get(key, key)
        mark = "✅" if value >= report.fail_under else "❌"
        lines.append(f"| {label} | `{value:.3f}` | {mark} |")

    lines.append("")
    if report.recorded_cost_usd is not None or report.recorded_tokens is not None:
        rec = report.recorded_cost_usd or 0.0
        saved = report.saved_cost_usd
        saved_str = f" • **saved** ${saved:.4f}" if saved is not None else ""
        lines.append(
            f"**Cost** — recorded (live) ${rec:.4f} • this run "
            f"${report.simulated_cost_usd:.4f} (replayed){saved_str}",
        )
    else:
        lines.append("**Cost** — replayed deterministically at $0 (no live API calls).")

    lines.append("")
    lines.append(
        f"<sub>baseline `{report.baseline_run_id}` • generated by "
        "[Volo](https://github.com/abhay-codes07/VOLO)</sub>",
    )
    return "\n".join(lines) + "\n"
